// Container Management Constants
export const CONTAINER_TYPES = {
  WOODEN_BARREL: 'WOODEN_BARREL',
  METAL_DRUM: 'METAL_DRUM',
  SQUARE_TANK: 'SQUARE_TANK',
  TOTE: 'TOTE',
  FIVE_GALLON_TOTE: 'FIVE_GALLON_TOTE',
  STILL: 'STILL',
  FERMENTER: 'FERMENTER'
};

// Container capacity in wine gallons
export const CONTAINER_CAPACITIES_GALLONS: Record<string, number> = {
  wooden_barrel: 53,
  metal_drum: 55,
  square_tank: 275,
  tote: 250,
  five_gallon_tote: 5,
  still: 100,
  fermenter: 500,
};

export const CONTAINER_STATUS = {
  EMPTY: 'EMPTY',
  FILLED: 'FILLED',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE',
  DAMAGED: 'DAMAGED'
};

// Product Management Constants
export const PRODUCT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DISCONTINUED: 'DISCONTINUED'
};

export const BATCH_TYPES = {
  FERMENTATION: 'FERMENTATION',
  DISTILLATION: 'DISTILLATION'
};

export const BATCH_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

// Transaction Types
export const TRANSACTION_TYPES = {
  // Container Operations
  CREATE_EMPTY_CONTAINER: 'CREATE_EMPTY_CONTAINER',
  CREATE_FILLED_CONTAINER: 'CREATE_FILLED_CONTAINER',
  EDIT_EMPTY_DATA_CORRECTION: 'EDIT_EMPTY_DATA_CORRECTION',
  EDIT_FILL_DATA_CORRECTION: 'EDIT_FILL_DATA_CORRECTION',
  EDIT_FILL_FROM_EMPTY: 'EDIT_FILL_FROM_EMPTY',
  EDIT_EMPTY_FROM_FILLED: 'EDIT_EMPTY_FROM_FILLED',
  REFILL_CONTAINER: 'REFILL_CONTAINER',
  
  // Transfers
  TRANSFER_IN: 'TRANSFER_IN',
  TRANSFER_OUT: 'TRANSFER_OUT',
  
  // Adjustments
  SAMPLE_ADJUST: 'SAMPLE_ADJUST',
  PROOF_DOWN: 'PROOF_DOWN',
  
  // Bottling
  BOTTLE_KEEP: 'BOTTLE_KEEP',
  BOTTLE_EMPTY: 'BOTTLE_EMPTY',
  BOTTLING_GAIN: 'BOTTLING_GAIN',
  BOTTLING_LOSS: 'BOTTLING_LOSS',
  
  // Production
  PRODUCTION: 'PRODUCTION',
  DISTILLATION_FINISH: 'DISTILLATION_FINISH',
  
  // Products
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_PRODUCTION_BATCH: 'DELETE_PRODUCTION_BATCH',
  CHANGE_ACCOUNT: 'CHANGE_ACCOUNT'
};

// Barrel Management Constants
export const BARREL_STATUS = {
  EMPTY: 'EMPTY',
  FILLED: 'FILLED',
  DUMPED: 'DUMPED',
  TRANSFERRED: 'TRANSFERRED',
  DAMAGED: 'DAMAGED'
};

export const BARREL_LOG_TYPES = {
  FILL: 'FILL',
  DUMP: 'DUMP',
  TRANSFER: 'TRANSFER',
  SAMPLING: 'SAMPLING',
  INSPECTION: 'INSPECTION',
  MAINTENANCE: 'MAINTENANCE',
  ADJUSTMENT: 'ADJUSTMENT'
};

// Processing Constants
export const BATCHING_TYPES = {
  BLENDING: 'BLENDING',
  FILTERING: 'FILTERING',
  CHILL_FILTERING: 'CHILL_FILTERING',
  CARBON_FILTERING: 'CARBON_FILTERING',
  FINISHING: 'FINISHING'
};

export const BATCHING_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

export const BOTTLING_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

// Transfer In Bond Constants
export const TRANSFER_TYPES = {
  BARREL: 'BARREL',
  CONTAINER: 'CONTAINER',
  TOTE: 'TOTE',
  TANKER: 'TANKER'
};

export const TRANSFER_DIRECTIONS = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND'
};

export const TRANSFER_STATUS = {
  PENDING: 'PENDING',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

// Finished Goods Constants
export const FINISHED_GOODS_STATUS = {
  IN_WAREHOUSE: 'IN_WAREHOUSE',
  SHIPPED: 'SHIPPED',
  RETURNED: 'RETURNED',
  DAMAGED: 'DAMAGED'
};

export const DEPLETION_TYPES = {
  SALE: 'SALE',
  SAMPLE: 'SAMPLE',
  DAMAGE: 'DAMAGE',
  THEFT: 'THEFT',
  RETURN: 'RETURN',
  ADJUSTMENT: 'ADJUSTMENT'
};

// Tank Management Constants
export const TANK_TYPES = {
  STORAGE: 'STORAGE',
  BLENDING: 'BLENDING',
  FINISHING: 'FINISHING',
  FILTERING: 'FILTERING',
  TEMPORARY: 'TEMPORARY'
};

export const TANK_STATUS = {
  EMPTY: 'EMPTY',
  FILLED: 'FILLED',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE'
};

export const TANK_LOG_TYPES = {
  FILL: 'FILL',
  EMPTY: 'EMPTY',
  TRANSFER: 'TRANSFER',
  FILTER: 'FILTER',
  ADJUST: 'ADJUST',
  MAINTENANCE: 'MAINTENANCE',
  SAMPLING: 'SAMPLING'
};

// TTB Reports Constants
export const TTB_REPORT_TYPES = {
  MONTHLY_PRODUCTION: 'MONTHLY_PRODUCTION',
  MONTHLY_INVENTORY: 'MONTHLY_INVENTORY',
  ANNUAL_PRODUCTION: 'ANNUAL_PRODUCTION',
  SPECIAL_REPORT: 'SPECIAL_REPORT'
};

export const TTB_REPORT_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  AMENDED: 'AMENDED'
};
